export const SERACH_START = 'SEARCH_START';

export const FETCH_SUGGESTIONS = 'FETCH_SUGGESTIONS';
//export const FETCH_SUGGESTIONS_INIT = 'FETCH_SUGGESTIONS_INIT';
export const FETCH_SUGGESTIONS_START = 'FETCH_SUGGESTIONS_START';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_SUGGESTIONS_FAIL = 'FETCH_SUGGESTIONS_FAIL';
export const FETCH_SUGGESTIONS_EXTEND = 'FETCH_SUGGESTIONS_EXTEND';
export const FETCH_SUGGESTIONS_FOLD = 'FETCH_SUGGESTIONS_FOLD';

export const SET_CITY_INFO = 'SET_CITY_INFO';

export const FETCH_WEATHERS = 'FETCH_WEATHERS';
export const FETCH_WEATHERS_START = 'FETCH_WEATHERS_START';
export const FETCH_WEATHERS_SUCCESS = 'FETCH_WEATHERS_SUCCESS';
export const FETCH_WEATHERS_FAIL = 'FETCH_WEATHERS_FAIL';

export const FETCH_WEATHERS_DAILY = 'FETCH_WEATHERS_DAILY';
export const FETCH_WEATHERS_DAILY_START = 'FETCH_WEATHERS_DAILY_START';
export const FETCH_WEATHERS_DAILY_SUCCESS = 'FETCH_WEATHERS_DAILY_SUCCESS';
export const FETCH_WEATHERS_DAILY_FAIL = 'FETCH_WEATHERS_DAILY_FAIL';

export const FETCH_TIMEZONE = 'FETCH_TIMEZONE';
export const FETCH_TIMEZONE_SUCCUESS = 'FETCH_TIMEZONE_SUCCUESS';
export const FETCH_TIMEZONE_FAIL = 'FETCH_TIMEZONE_FAIL';

