export const SERACH_START = 'SEARCH_START';

export const FETCH_SUGGESTIONS = 'FETCH_SUGGESTIONS';
//export const FETCH_SUGGESTIONS_INIT = 'FETCH_SUGGESTIONS_INIT';
export const FETCH_SUGGESTIONS_START = 'FETCH_SUGGESTIONS_START';
export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS';
export const FETCH_SUGGESTIONS_FAIL = 'FETCH_SUGGESTIONS_FAIL';
export const FETCH_SUGGESTIONS_EXTEND = 'FETCH_SUGGESTIONS_EXTEND';
export const FETCH_SUGGESTIONS_FOLD = 'FETCH_SUGGESTIONS_FOLD';

export const FETCH_WEATHERS = 'FETCH_WEATHERS';
export const FETCH_WEATHERS_START = 'FETCH_WEATHERS_START';
export const FETCH_WEATHERS_SUCCESS = 'FETCH_WEATHERS_SUCCESS';
export const FETCH_WEATHERS_FAIL = 'FETCH_WEATHERS_FAIL';

